#spring.application.name=ktMINESAPIs

bulkApiUrl = https://api.ktmine.com/api/v2/patents/bulk
searchApiUrl = https://api.ktmine.com/api/v2/patents/search
pdfApiUrl = https://api.ktmine.com/api/v2/patents/pdf/%s?key=%s
pngApiUrl = https://api.ktmine.com/api/v2/patents/png/%s?key=%s&reductionPercentage=%s&imagePath=%s

openai.api.key = xxxxxxxxxx